import re
pattern = r'Genesis (\d+)'
matches_list = ["Bible","Old Testament","Genesis","Genesis 1","Genesis 2"]
# matches_string = ", ".join(matches_list)
# matches = re.fullmatch(pattern, matches_string)

#print(matches_string)

for match in matches_list:
                matches = re.fullmatch(pattern, match)
                #print(matches)
                if matches:
                    print("regex works")
                    print(matches.group(1))
                #if match == "Genesis 1" or match == "Gen. 1":
                #   print("Genesis 1 runs")
                # if match == "Genesis 2" or match == "Gen. 2":
                    # print("Genesis 2 runs")
scripture_names = ["Bible","Genesis","Gen.","Exodus","Ex.","Leviticus","Lev.","Numbers","Num.","Deuteronomy","Joshua","Josh.",
                   "Judges","Judg.","Ruth","Rut.","1 Samuel","1 Sam.","2 Samuel","2 Sam.","1 Kings","2 Kings",'1 Chronicles','1 Chr.',
                   '2 Chronicles','2 Chr.','Ezra','Nehemiah','Neh.','Esther','Job','Psalms','Psalm','Ps.','Proverbs','Prov.','Ecclesiastes',
                   'Song of Solomon','Song.','Isaiah','Isa.','Jeremiah','Jer.','Lamentations','Lam.','Ezekiel','Ezek.','Daniel','Dan.',
                   'Hosea','Joel','Amos','Obadiah 1','Jonah','Micah','Nahum','Nehemiah','Habakkuk','Hab.','Zephaniah','Zeph.','Haggai','Hag.','Zechariah','Zech.',
                   'Malachi','Mal.','1 Nephi','1 Ne.','2 Nephi','2 Ne.','Jacob','Enos 1','Jarom 1','Omni 1','Words of Mormon','W of M',
                   'Mosiah','Alma','Helaman','Hel.','3 Nephi','3 Ne.','4 Nephi','4 Ne.','Book of Mormon','Morm.','Ether','Moro.','Moroni','New Testament',
                   'Matthew','Matt.','Mark','Luke','Gospels of John','John','Acts','Romans','Rom.','1 Corinthians','1 Cor.','2 Corinthians','2 Cor.',
                   'Galatians','Gal.','Ephesians','Eph.','Philippians','Philip.','Colossians','Col.','1 Thessalonians','1 Thes.','2 Thessalonians','2 Thes.',
                   '1 Timothy','1 Tim.','2 Timothy','2 Tim.','Titus','Philemon','Philem.','Hebrews','Heb.','James','1 Peter','1 Pet.','2 Peter','2 Pet.',
                   '1 John','1 Jn.','2 John','2 Jn.','3 John','3 Jn.','Jude 1','Revelation','Rev.','Doctrine and Covenants','D&C','Moses','Abraham','Abr.',
                   'Facsimile','Joseph Smith-Matthew','JS-M','Joseph Smith History','Joseph Smith—History','Articles of Faith','A of F','Joseph Smith Translation',
                   'JST','Ten Commandments','10 Commandments','Title Page of the Book of Mormon','Testimony of the Twelve Apostles from the Book of Mormon']
print(len(scripture_names))




# pattern_genesis = r'Genesis (\d+)'
# pattern_genesis = r'Gen. (\d+)'
# pattern_exodus = r'Exodus (\d+)'
# pattern_exodus = r'Ex. (\d+)'
# pattern_leviticus = r'Leviticus (\d+)'
# pattern_leviticus = r'Lev. (\d+)'
# pattern_numbers = r'Numbers (\d+)'
# pattern_numbers = r'Num. (\d+)'
# pattern_deuteronomy = r'Deuteronomy (\d+)'
# pattern_joshua = r'Joshua (\d+)'
# pattern_joshua = r'Josh. (\d+)'
# pattern_judges = r'Judges (\d+)'
# pattern_judges = r'Judg. (\d+)'
# pattern_ruth = r'Ruth (\d+)'
# pattern_ruth = r'Rut. (\d+)'
# pattern_first_samuel = r'1 Samuel (\d+)'
# pattern_first_samuel = r'1 Sam. (\d+)'
# pattern_second_samuel = r'2 Samuel (\d+)'
# pattern_second_samuel = r'2 Sam. (\d+)'
# pattern_first_kings = r'1 Kings (\d+)'
# pattern_second_kings = r'2 Kings (\d+)'
# pattern_first_chronicles = r'1 Chronicles (\d+)'
# pattern_first_chronicles = r'1 Chr. (\d+)'
# pattern_second_chronicles = r'2 Chronicles (\d+)'
# pattern_second_chronicles = r'2 Chr. (\d+)'
# pattern_ezra = r'Ezra (\d+)'
# pattern_nehemiah = r'Nehemiah (\d+)'
# pattern_nehemiah = r'Neh. (\d+)'
# pattern_esther = r'Esther (\d+)'
# pattern_job = r'Job (\d+)'
# pattern_psalms = r'Psalms (\d+)'
# pattern_psalms = r'Psalm (\d+)'
# pattern_psalms = r'Ps. (\d+)'
# pattern_proverbs = r'Proverbs (\d+)'
# pattern_proverbs = r'Prov. (\d+)'
# pattern_ecclesiastes = r'Ecclesiastes (\d+)'
# pattern_song_of_solomon = r'Song of Solomon (\d+)'
# pattern_song_of_solomon = r'Song. (\d+)'
# pattern_isaiah = r'Isaiah (\d+)'
# pattern_isaiah = r'Isa. (\d+)'
# pattern_jeremiah = r'Jeremiah (\d+)'
# pattern_jeremiah = r'Jer. (\d+)'
# pattern_lamentation = r'Lamentations (\d+)'
# pattern_lamentation = r'Lam. (\d+)'
# pattern_ezekiel = r'Ezekiel (\d+)'
# pattern_ezekiel = r'Ezek. (\d+)'
# pattern_daniel = r'Daniel (\d+)'
# pattern_daniel = r'Dan. (\d+)'
# pattern_hosea = r'Hosea (\d+)'
# pattern_joel = r'Joel (\d+)'
# pattern_amos = r'Amos (\d+)'
# pattern_jonah = r'Jonah (\d+)'
# pattern_micah = r'Micah (\d+)'
# pattern_nahum = r'Nahum (\d+)'
# pattern_nehemiah = r'Nehemiah (\d+)'
# pattern_habakkuk = r'Habakkuk (\d+)'
# pattern_habakkuk = r'Hab. (\d+)'
# pattern_zephaniah = r'Zephaniah (\d+)'
# pattern_zephaniah = r'Zeph. (\d+)'
# pattern_haggai = r'Haggai (\d+)'
# pattern_haggai = r'Hag. (\d+)'
# pattern_zechariah = r'Zechariah (\d+)'
# pattern_zechariah = r'Zech. (\d+)'
# pattern_malachi = r'Malachi (\d+)'
# pattern_malachi = r'Mal. (\d+)'
# pattern_first_nephi = r'1 Nephi (\d+)'
# pattern_first_nephi = r'1 Ne. (\d+)'
# pattern_second_nephi = r'2 Nephi (\d+)'
# pattern_second_nephi = r'2 Ne. (\d+)'
# pattern_jacob = r'Jacob (\d+)'
# pattern_words_of_mormon = r'Words of Mormon (\d+)'
# pattern_words_of_mormon = r'W of M (\d+)'
# pattern_mosiah = r'Mosiah (\d+)'
# pattern_alma = r'Alma (\d+)'
# pattern_helaman = r'Helaman (\d+)'
# pattern_helaman = r'Hel. (\d+)'
# pattern_third_nephi = r'3 Nephi (\d+)'
# pattern_third_neph = r'3 Ne. (\d+)'
# pattern_book_of_mormon = r'Book of Mormon (\d+)'
# pattern_mormon = r'Morm. (\d+)'
# pattern_ether = r'Ether (\d+)'
# pattern_moroni = r'Moroni (\d+)'
# pattern_new_testament = r'New Testament (\d+)'
# pattern_matthew = r'Matthew (\d+)'
# pattern_matthew = r'Matt. (\d+)'
# pattern_mark = r'Mark (\d+)'
# pattern_luke = r'Luke (\d+)'
# pattern_john = r'Gospels of John (\d+)'
# pattern_john = r'John (\d+)'
# pattern_acts = r'Acts (\d+)'
# pattern_romans = r'Romans (\d+)'
# pattern_romans = r'Rom. (\d+)'
# pattern_first_corinthians = r'1 Corinthians (\d+)'
# pattern_first_corinthians = r'1 Cor. (\d+)'
# pattern_second_corinthians = r'2 Corinthians (\d+)'
# pattern_second_corinthians = r'2 Cor. (\d+)'
# pattern_galatians = r'Galatians (\d+)'
# pattern_galatians = r'Gal. (\d+)'
# pattern_ephesians = r'Ephesians (\d+)'
# pattern_ephesians = r'Eph. (\d+)'
# pattern_philippians = r'Philippians (\d+)'
# pattern_philippians = r'Philip. (\d+)'
# pattern_colossians = r'Colossians (\d+)'
# pattern_colossians = r'Col. (\d+)'
# pattern_first_thessalonians = r'1 Thessalonians (\d+)'
# pattern_first_thessalonians = r'1 Thes. (\d+)'
# pattern_second_thessalonians = r'2 Thessalonians(\d+)'
# pattern_second_thessalonians = r'2 Thes. (\d+)'
# pattern_first_timothy = r'1 Timothy (\d+)'
# pattern_first_timothy = r'1 Tim. (\d+)'
# pattern_second_timothy = r'2 Timothy (\d+)'
# pattern_second_timothy = r'2 Tim. (\d+)'
# pattern_titus = r'Titus (\d+)'
# pattern_hebrews = r'Hebrews (\d+)'
# pattern_hebrews = r'Heb. (\d+)'
# pattern_james = r'James (\d+)'
# pattern_first_peter = r'1 Peter (\d+)'
# pattern_first_peter = r'1 Pet. (\d+)'
# pattern_second_peter = r'2 Peter (\d+)'
# pattern_second_peter = r'2 Pet. (\d+)'
# pattern_first_john = r'1 John (\d+)'
# pattern_first_john = r'1 Jn. (\d+)'
# pattern_third_john = r'3 John (\d+)'
# pattern_third_john = r'3 Jn. (\d+)'
# pattern_revelation = r'Revelation (\d+)'
# pattern_revelation = r'Rev. (\d+)'
# pattern_doctrine_and_covenants = r'Doctrine and Covenants (\d+)'
# pattern_doctrine_and_covenants = r'D&C (\d+)'
# pattern_moses = r'Moses (\d+)'
# pattern_abraham = r'Abraham (\d+)'
# pattern_abraham = r'Abr. (\d+)'
# pattern_facimile = r'Facsimile (\d+)'
# pattern_joseph_smith_translation = r'Joseph Smith Translation (\d+)'
# pattern_joseph_smith_translation = r'JST (\d+)'





# pattern_genesis = r'Genesis (\d+)|Gen. (\d+)'
# pattern_exodus = r'Exodus (\d+)|Ex. (\d+)'
# pattern_leviticus = r'Leviticus (\d+)|Lev. (\d+)'
# pattern_numbers = r'Numbers (\d+)|Num. (\d+)'
# pattern_deuteronomy = r'Deuteronomy (\d+)'
# pattern_joshua = r'Joshua (\d+)|Josh. (\d+)'
# pattern_judges = r'Judges (\d+)|Judg. (\d+)'
# pattern_ruth = r'Ruth (\d+)|Rut. (\d+)'
# pattern_first_samuel = r'1 Samuel (\d+)|1 Sam. (\d+)'
# pattern_second_samuel = r'2 Samuel (\d+)|2 Sam. (\d+)'
# pattern_first_kings = r'1 Kings (\d+)'
# pattern_second_kings = r'2 Kings (\d+)'
# pattern_first_chronicles = r'1 Chronicles (\d+)|1 Chr. (\d+)'
# pattern_second_chronicles = r'2 Chronicles (\d+)|2 Chr. (\d+)'
# pattern_ezra = r'Ezra (\d+)'
# pattern_nehemiah = r'Nehemiah (\d+)|Neh. (\d+)'
# pattern_esther = r'Esther (\d+)'
# pattern_job = r'Job (\d+)'
# pattern_psalms = r'Psalms (\d+)|Psalm (\d+)|Ps. (\d+)'
# pattern_proverbs = r'Proverbs (\d+)|Prov. (\d+)'
# pattern_ecclesiastes = r'Ecclesiastes (\d+)'
# pattern_song_of_solomon = r'Song of Solomon (\d+)|Song. (\d+)'
# pattern_isaiah = r'Isaiah (\d+)|Isa. (\d+)'
# pattern_jeremiah = r'Jeremiah (\d+)|Jer. (\d+)'
# pattern_lamentation = r'Lamentations (\d+)|Lam. (\d+)'
# pattern_ezekiel = r'Ezekiel (\d+)|Ezek. (\d+)'
# pattern_daniel = r'Daniel (\d+)|Dan. (\d+)'
# pattern_hosea = r'Hosea (\d+)'
# pattern_joel = r'Joel (\d+)'
# pattern_amos = r'Amos (\d+)'
# pattern_jonah = r'Jonah (\d+)'
# pattern_micah = r'Micah (\d+)'
# pattern_nahum = r'Nahum (\d+)|Nah. (\d+)'
# pattern_habakkuk = r'Habakkuk (\d+)|Hab. (\d+)'
# pattern_zephaniah = r'Zephaniah (\d+)|Zeph. (\d+)'
# pattern_haggai = r'Haggai (\d+)|Hag. (\d+)'
# pattern_zechariah = r'Zechariah (\d+)|Zech. (\d+)'
# pattern_malachi = r'Malachi (\d+)|Mal. (\d+)'
# pattern_first_nephi = r'1 Nephi (\d+)|1 Ne. (\d+)'
# pattern_second_nephi = r'2 Nephi (\d+)|2 Ne. (\d+)'
# pattern_jacob = r'Jacob (\d+)'
# pattern_words_of_mormon = r'Words of Mormon (\d+)|W of M (\d+)'
# pattern_mosiah = r'Mosiah (\d+)'
# pattern_alma = r'Alma (\d+)'
# pattern_helaman = r'Helaman (\d+)|Hel. (\d+)'
# pattern_third_nephi = r'3 Nephi (\d+)|3 Ne. (\d+)'
# pattern_mormon = r'Morm. (\d+)'
# pattern_ether = r'Ether (\d+)'
# pattern_moroni = r'Moroni (\d+)'
# pattern_matthew = r'Matthew (\d+)|Matt. (\d+)'
# pattern_mark = r'Mark (\d+)'
# pattern_luke = r'Luke (\d+)'
# pattern_john = r'Gospels of John (\d+)|John (\d+)'
# pattern_acts = r'Acts (\d+)'
# pattern_romans = r'Romans (\d+)|Rom. (\d+)'
# pattern_first_corinthians = r'1 Corinthians (\d+)|1 Cor. (\d+)'
# pattern_second_corinthians = r'2 Corinthians (\d+)|2 Cor. (\d+)'
# pattern_galatians = r'Galatians (\d+)|Gal. (\d+)'
# pattern_ephesians = r'Ephesians (\d+)|Eph. (\d+)'
# pattern_philippians = r'Philippians (\d+)|Philip. (\d+)'
# pattern_colossians = r'Colossians (\d+)|Col. (\d+)'
# pattern_first_thessalonians = r'1 Thessalonians (\d+)|1 Thes. (\d+)'
# pattern_second_thessalonians = r'2 Thessalonians(\d+)|2 Thes. (\d+)'
# pattern_first_timothy = r'1 Timothy (\d+)|1 Tim. (\d+)'
# pattern_second_timothy = r'2 Timothy (\d+)|2 Tim. (\d+)'
# pattern_titus = r'Titus (\d+)'
# pattern_hebrews = r'Hebrews (\d+)|Heb. (\d+)'
# pattern_james = r'James (\d+)'
# pattern_first_peter = r'1 Peter (\d+)|1 Pet. (\d+)'
# pattern_second_peter = r'2 Peter (\d+)|2 Pet. (\d+)'
# pattern_first_john = r'1 John (\d+)|1 Jn. (\d+)'
# pattern_third_john = r'3 John (\d+)|3 Jn. (\d+)'
# pattern_revelation = r'Revelation (\d+)|Rev. (\d+)'
# pattern_doctrine_and_covenants = r'Doctrine and Covenants (\d+)|D&C (\d+)'
# pattern_moses = r'Moses (\d+)'
# pattern_abraham = r'Abraham (\d+)|Abr. (\d+)'
# pattern_facimile = r'Facsimile (\d+)'
# pattern_joseph_smith_translation = r'Joseph Smith Translation (\d+)|JST (\d+)'



match_joseph_smith_translation = re.fullmatch(pattern_joseph_smith_translation, match)